### ISSUE TITLE
Add query info to return

### ISSUE THREAD

**Issue by dschristianson** [BASIN-3D/basin3d#96]
**Is your feature request related to a problem? Please describe.**
Query information should be added to the return to provide more transparency

See #90 for related notes.

**Comment by vchendrix** [comment]
This will be a structural change that will require changing the list call for data model access to be a response data structure.

## DataSourceModelAccess.list
refactor the list method to return the list inside a new data structure
```yaml
Basin3dResponse:
  .. other additions here ..
  queryInfo: <dict of params>
  errors: <data structure for errors> Default is empty or null
  results: <list of data items>
```
